require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-minitest
  - rubocop-factory_bot

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/**/*
    - vendor/**/*
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Rails/I18nLocaleTexts:
  Enabled: false

Minitest/MultipleAssertions:
  Exclude:
    - test/system/**/*
    - test/mailers/*

Metrics/BlockLength:
  Exclude:
    - test/**/*
    - config/environments/*
    - config/routes.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*

Lint/MissingSuper:
  Exclude:
    - app/services/**/*

Capybara/ClickLinkOrButtonStyle:
  EnforcedStyle: strict
